### ISSUE TITLE
`@sapui5/ts-types-esm` - compile errors with typescript `strict` flag

### ISSUE THREAD

**Issue by DetachHead** [SAP/ui5-typescript#315]
### `tsc` output
```
node_modules/@sapui5/ts-types-esm/types/sap.ui.comp.d.ts:3412:5 - error TS2416: Property 'getVisibleInFilterBar' in type 'FilterGroupItem' is not assignable to the same property in base type 'FilterItem'.
  Type 'undefined' is not assignable to type '() => boolean'.

3412     getVisibleInFilterBar: undefined;
         ~~~~~~~~~~~~~~~~~~~~~

node_modules/@sapui5/ts-types-esm/types/sap.ui.comp.d.ts:15766:5 - error TS2416: Property 'search' in type 'SmartFilterBar' is not assignable to the same property in base type 'FilterBar'.
  Type '(bSync?: boolean | undefined) => boolean | undefined' is not assignable to type '() => boolean'.
    Type 'boolean | undefined' is not assignable to type 'boolean'.
      Type 'undefined' is not assignable to type 'boolean'.

15766     search(
          ~~~~~~

node_modules/@sapui5/ts-types-esm/types/sap.ui.core.d.ts:33177:5 - error TS2416: Property 'getId' in type 'UIArea' is not assignable to the same property in base type 'ManagedObject'.
  Type '() => string | null' is not assignable to type '() => string'.
    Type 'string | null' is not assignable to type 'string'.
      Type 'null' is not assignable to type 'string'.

33177     getId(): string | null;
          ~~~~~

node_modules/@sapui5/ts-types-esm/types/sap.ui.vtm.d.ts:665:5 - error TS2416: Property 'setTooltip' in type 'Column' is not assignable to the same property in base type 'UI5Element'.
  Type '(sTooltip?: string | undefined) => this' is not assignable to type '(vTooltip: string | TooltipBase) => this'.
    Types of parameters 'sTooltip' and 'vTooltip' are incompatible.
      Type 'string | TooltipBase' is not assignable to type 'string | undefined'.
        Type 'TooltipBase' is not assignable to type 'string'.

665     setTooltip(
        ~~~~~~~~~~
```
### tsconfig
```json
{
    "compilerOptions": {
        "target": "es2018",
        "module": "es2015",
        "moduleResolution": "node",
        "declaration": true,
        "declarationMap": false,
        "skipLibCheck": false,
        "preserveConstEnums": true,
        "sourceMap": false,
        "allowJs": false,
        "strict": true,
        "strictNullChecks": true,
        "strictPropertyInitialization": true,
        "noImplicitAny": true,
        "strictFunctionTypes": true,
        "strictBindCallApply": true,
        "noImplicitThis": true,
        "alwaysStrict": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "noUncheckedIndexedAccess": true,
        "forceConsistentCasingInFileNames": true,
        "noPropertyAccessFromIndexSignature": true,
        "noImplicitOverride": true,
        "exactOptionalPropertyTypes": false,
        "allowUnreachableCode": false,
        "stripInternal": false,
        "esModuleInterop": true,
        "rootDir": "./src",
        "outDir": "./dist",
        "noEmit": true,
        "baseUrl": "./",
        "isolatedModules": true,
        "resolveJsonModule": true,
        "typeRoots": ["./node_modules/@types", "./node_modules/@sapui5/ts-types-esm"],
        "paths": {
            "thirdparty/*": ["./node_modules/*"]
        }
    },
    "include": ["./src/**/*", "./types/**/*"]
}
```

**Comment by akudev** [comment]
Thanks for the report! The issue with UIArea.getId() is already fixed and will be gone with the type definitions for the next release (was reported also in https://github.com/SAP/ui5-typescript/issues/286) OpenUI5 will thus be fully covered in strict mode.
We'll need to look at the other problems, though, which were not reported back then.

**Comment by akudev** [comment]
I have to take back the "OpenUI5 will thus be fully covered in strict mode" for 1.97: there's still one issue with v2.ODataModel.createBindingContext(), which interestingly was neither reported by you nor in the other issue report and also slipped through on our side.
The third issue in your list is now fixed, though. 
(fixing this kind of issues is often hard because we cannot change APIs incompatibly and documentation needs to reflect the API behavior)

**Comment by akudev** [comment]
The ODataModel.createBindingContext issue is fixed in https://github.com/SAP/openui5/commit/5a4d90ec5b314f210c035e85212b98ceefb05d3a

**Comment by akudev** [comment]
With the just published version 1.98.0, full strict mode should be working fine.

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58429

**Comment by DetachHead** [comment]
@akudev one of the errors is still there in 1.98.0:

```
node_modules/@sapui5/ts-types-esm/types/sap.ui.comp.d.ts:15955:5 - error TS2416: Property 'search' in type 'SmartFilterBar' is not assignable to the same property in base type 'FilterBar'.
  Type '(bSync?: boolean | undefined) => boolean | undefined' is not assignable to type '() => boolean'.                                                                                    
    Type 'boolean | undefined' is not assignable to type 'boolean'.                                                                                                                         
      Type 'undefined' is not assignable to type 'boolean'.                                                                                                                                 
                                                                                                                                                                                            
15955     search(                                                                                                                                                                           
          ~~~~~~  
```

can this issue be re-opened or should i raise a new one?

**Comment by akudev** [comment]
@DetachHead Erm... ok, I was referring to OpenUI5, as this repository is about OpenUI5 and at DefinitelyTyped, only the OpenUI5 types are published. sap.ui.comp is in SAPUI5 only.
But you mentioned SAPUI5 from the beginning, sorry.

The good news is that the SmartField issue has been fixed yesterday, along with the other remaining issue in sap.ui.vtm, which had so far only been hidden with @ts-ignore (which dtslint does not like at all). So the fix will be in 1.99. Codesplit is next Wednesday and the release for SAPUI5 is planned to happen around February 24th.

So the issue can remain closed - or do you prefer it re-opened and have it as a reminder for the release? I'd offer this as a sort of service because 1.98 disappointed you in this respect. ;-)

**Comment by DetachHead** [comment]
all good, i know you guys close issues as soon as they are fixed rather than when the fix is released. as long as it's been fixed that's fine with me :)
